name: BitBot Queue Pending Workflows (Self‑Healing)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  queue_pending:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Locate get_pending_workflows.py
        id: find_get
        run: |
          echo "🔍 Searching for get_pending_workflows.py..."
          SCRIPT_PATH=$(find . -type f -iname "get_pending_workflows.py" | head -n 1)
          if [ -z "$SCRIPT_PATH" ]; then
            echo "❌ ERROR: get_pending_workflows.py not found anywhere in repo."
            exit 1
          fi
          echo "✅ Found at: $SCRIPT_PATH"
          echo "script_path=$SCRIPT_PATH" >> $GITHUB_OUTPUT

      - name: Locate deploy_bitbot_agent.py
        id: find_deploy
        run: |
          echo "🔍 Searching for deploy_bitbot_agent.py..."
          SCRIPT_PATH=$(find . -type f -iname "deploy_bitbot_agent.py" | head -n 1)
          if [ -z "$SCRIPT_PATH" ]; then
            echo "❌ ERROR: deploy_bitbot_agent.py not found anywhere in repo."
            exit 1
          fi
          echo "✅ Found at: $SCRIPT_PATH"
          echo "script_path=$SCRIPT_PATH" >> $GITHUB_OUTPUT

      - name: Locate run_pending_with_bitbot.py
        id: find_run
        run: |
          echo "🔍 Searching for run_pending_with_bitbot.py..."
          SCRIPT_PATH=$(find . -type f -iname "run_pending_with_bitbot.py" | head -n 1)
          if [ -z "$SCRIPT_PATH" ]; then
            echo "❌ ERROR: run_pending_with_bitbot.py not found anywhere in repo."
            exit 1
          fi
          echo "✅ Found at: $SCRIPT_PATH"
          echo "script_path=$SCRIPT_PATH" >> $GITHUB_OUTPUT

      - name: Get Pending Workflows
        run: |
          python "${{ steps.find_get.outputs.script_path }}" > pending_wfs.json

      - name: Deploy BitBot Agents for Pending
        run: |
          python "${{ steps.find_deploy.outputs.script_path }}" \
            --input pending_wfs.json \
            --pattern ml.patterns.learn.bitbot.bit

      - name: Run Pending Workflows on BitBot
        run: |
          python "${{ steps.find_run.outputs.script_path }}" \
            --input pending_wfs.json
